data_compliance_task:
  description: >
    分析{data}文件中的用户租房需求，结合澳洲租房市场实际情况和知识库中的信息，识别不合理或不符合市场规律的需求项。
  expected_output: >
    一份详细的不符合项列表，每个项目包含：不符合的具体内容、基于澳洲租房市场实际情况的专业分析。
  agent: data_compliance_agent

inquiry_task:
  description: >
    根据澳洲租房市场实际情况和知识库中的信息，引导用户修改{data}中的需求，使其更加合理可行。
  expected_output: >
    一个符合{data}格式的JSON文件，其中包含经过优化的用户需求，更符合澳洲租房市场的实际情况。
  agent: inquiry_agent

reporting_task:
  description: >
    基于{data}文件和知识库中的信息，生成一份全面的租房分析报告。
  expected_output: >
    一份结构化的中文markdown报告，包含以下部分：
    1. 需求分析 - 用户预算和偏好评估
    2. 市场概况 - 澳洲租房市场实际情况
    3. 区域推荐 - 基于用户需求的区域建议
    4. 房型建议 - 性价比分析和房型推荐
    5. 合同指南 - 租期、押金等注意事项
    6. 风险提示 - 租房过程中需要注意的问题
    报告应格式清晰，内容专业，并且完全使用中文。
  agent: reporting_agent
